### ISSUE TITLE
not claim on ubuntu 16.04

### ISSUE THREAD

**Issue by umberto12345** [renowator/CryptosFaucets_Bot#17]
After 1 day usage the error is  but if i enter on site i can claim

6|console_bot  | Error was encountered on:  https://freeethereum.com/set-language/en
6|console_bot  | Error: No node found for selector: input[name=email]
6|console_bot  |   👎 FAIL. Coin not claimed. ❌
6|console_bot  | Error was encountered on:  https://free-ltc.com/set-language/en
6|console_bot  | Error: No node found for selector: input[name=email]
6|console_bot  |   👎 FAIL. Coin not claimed. ❌
6|console_bot  | Error was encountered on:  https://freebitcoin.io/set-language/en
6|console_bot  | Error: No node found for selector: input[name=email]
6|console_bot  |   👎 FAIL. Coin not claimed. ❌

**Comment by renowator** [comment]
The site sometimes blocks ip addresses, then ip is unblocked

**Comment by Tiebe** [comment]
Reopen please. This is not the solution. A bot like this one should evade protections like these. It shouldn't even be flagged! I'm sorry, but I'm going to be a bit annoying here, @renowator. You should take care of your code, and especially make sure you know what it does. If you accept a pull request you can't just say that it's not your code so you can't help someone with their problem. Please do this the right way!

**Comment by renowator** [comment]
**** The IP block is something i cannot do anything about, this is performed by site owners when too many claims are made from single IP ****

FYI I dont get paid for this:

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
